CREATE TABLE ANIMAL (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    RACA VARCHAR2(50),
    DATA_NASCIMENTO DATE,
    OBSERVACAO_GERAL VARCHAR2(500),
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE ACao_PREVENTIVA (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ANIMAL_ID RAW(16) NOT NULL,
    NOME_SERVICO VARCHAR2(150) NOT NULL,
    DESCRICAO VARCHAR2(500) NOT NULL,
    PROXIMO_PREVISTO VARCHAR2(100),
    OBSERVACAO VARCHAR2(500),
    CATEGORIA VARCHAR2(50),
    DATA_HORA_REGISTRO TIMESTAMP,
    CONSTRAINT FK_ACAO_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

CREATE TABLE ATIVIDADE_BEM_ESTAR (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ANIMAL_ID RAW(16) NOT NULL,
    ATIVIDADE VARCHAR2(150) NOT NULL,
    OBSERVACAO_ATIVIDADE VARCHAR2(500),
    DURACAO VARCHAR2(50),
    OBSERVACAO VARCHAR2(500),
    CATEGORIA VARCHAR2(100),
    DATA_HORA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_ATIVIDADE_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

CREATE TABLE REGISTRO_CUIDADO (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ANIMAL_ID RAW(16) NOT NULL,
    CATEGORIA VARCHAR2(50) NOT NULL,
    DESCRICAO VARCHAR2(500),
    DATA_HORA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_REGISTRO_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

CREATE TABLE TRATAMENTO_TERAPEUTICO (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ANIMAL_ID RAW(16) NOT NULL,
    MEDICAMENTO VARCHAR2(150) NOT NULL,
    DOSAGEM VARCHAR2(50),
    FREQUENCIA VARCHAR2(50),
    DURACAO_TRATAMENTO VARCHAR2(50),
    OBSERVACAO VARCHAR2(500),
    CATEGORIA VARCHAR2(100),
    DATA_HORA_REGISTRO TIMESTAMP NOT NULL,
    CONSTRAINT FK_TRATAMENTO_ANIMAL FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

CREATE TABLE USUARIO (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL
);