-- Criar tabela USUARIO se não existir
CREATE TABLE USUARIO (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ATIVO NUMBER(1) DEFAULT 1 NOT NULL
);

-- Inserir usuários
INSERT INTO USUARIO (ID, USERNAME, PASSWORD, ROLE, ATIVO)
VALUES (SYS_GUID(), 'admin', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', 'ADMIN', 1);

INSERT INTO USUARIO (ID, USERNAME, PASSWORD, ROLE, ATIVO)
VALUES (SYS_GUID(), 'user', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVKIUi', 'USER', 1);

COMMIT;